# Generated by Django 4.1 on 2023-12-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestBulk2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept_cd", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={"db_table": "test_bulk2", "managed": False,},
        ),
    ]
